#pragma once

#define IDC_MAIN_EDIT_PATH 101
#define IDC_BUTTON_UP 102
#define IDC_BUTTON_DOWN 103


#define IDC_FD_EDIT 104
#define IDC_FD_BTN_OK 105
#define IDC_FD_BTN_CANCEL 106
#define IDC_FD_BTN_BROWSE 107
#define IDC_FD_BTN_LOAD 114
#define IDC_FD_CBX_HEADER 108
#define IDC_FD_CBX_FNAME 109
#define IDC_FD_CBX_FSPEC 110
#define IDC_FD_EDT_HEADER 111
#define IDC_FD_EDT_FNAME 112
#define IDC_FD_EDT_FSPEC 113

#define IDC_CELL_EDIT 114


#define WM_USER_FIND_FILES (WM_USER+1)
#define WM_USER_EDIT_EXIT (WM_USER+2)
#define WM_LV_MOSE_SCROLL (WM_USER+3)
#define WM_SET_OLD_EDIT_PROC (WM_USER+4)
#define WM_GET_SYST_FONTS (WM_USER+5)
#define WM_USER_EDIT_INP (WM_USER+6)
#define WM_CREATE_TABLE (WM_USER+7)



#define WM_TBL_EVENTS (WM_USER+8)
#define WM_TBL_L_CLK (WM_TBL_EVENTS+0)
#define WM_TBL_LDBL_CLK (WM_TBL_EVENTS+1)
#define WM_TBL_R_CLK (WM_TBL_EVENTS+2)
#define WM_TBL_RDBL_CLK (WM_TBL_EVENTS+3)
#define WM_TBL_M_CLK (WM_TBL_EVENTS+4)



